import threading
from tkinter import *
from PIL import ImageTk,Image
import sudoku  #importing sudoko.py file for solving

solver=sudoku.Solver()

class GUI():

    #Location of images used...change it if you saved in other directory
    one = "images/one.jpeg"
    grid = "images/grid.png"
    
    def __init__(self):

        # Creating start window
        root = Tk()
        root.title("Sudoku Solver")
        root.resizable(0,0)
        img = ImageTk.PhotoImage(Image.open(self.one))
        lbl=Label(root,image=img)
        lbl.image = img
        lbl.grid(row=0,column=0,columnspan=6,rowspan=14)
        Button(root,text="Enter",fg="green",command=self.entries).grid(row=11,column=2,columnspan=2)
        Button(root,text="Exit",fg="red",command=root.destroy).grid(row=12,column=2,columnspan=2)
        Label(root,text="©Daniyal Dolare",font=("font9",10)).grid(row=15,column=4,columnspan=2)
        root.mainloop()

        #Creating window to enter the sudoku  
    def entries(self):
        self.top = Toplevel()
        self.top.resizable(0,0)
        
        self.e00 = Entry(self.top,width=2,font=("font9",16),justify='center')
        self.e01 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e02 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e03 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e04 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e05 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e06 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e07 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e08 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e10 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e11 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e12 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e13 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e14 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e15 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e16 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e17 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e18 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e20 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e21 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e22 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e23 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e24 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e25 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e26 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e27 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e28 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e30 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e31 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e32 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e33 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e34 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e35 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e36 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e37 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e38 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e40 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e41 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e42 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e43 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e44 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e45 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e46 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e47 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e48 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e50 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e51 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e52 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e53 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e54 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e55 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e56 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e57 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e58 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e60 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e61 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e62 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e63 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e64 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e65 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e66 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e67 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e68 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e70 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e71 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e72 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e73 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e74 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e75 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e76 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e77 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e78 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e80 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e81 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e82 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e83 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e84 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e85 = Entry(self.top,width=2,font=('font9',16),justify='center',background='#a5a5a5')
        self.e86 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e87 = Entry(self.top,width=2,font=('font9',16),justify='center')
        self.e88 = Entry(self.top,width=2,font=('font9',16),justify='center')
        
        self.e00.insert(0,'0')
        self.e01.insert(0,'0')
        self.e02.insert(0,'0')
        self.e03.insert(0,'0')
        self.e04.insert(0,'0')
        self.e05.insert(0,'0')
        self.e06.insert(0,'0')
        self.e07.insert(0,'0')
        self.e08.insert(0,'0')
        self.e10.insert(0,'0')
        self.e11.insert(0,'0')
        self.e12.insert(0,'0')
        self.e13.insert(0,'0')
        self.e14.insert(0,'0')
        self.e15.insert(0,'0')
        self.e16.insert(0,'0')
        self.e17.insert(0,'0')
        self.e18.insert(0,'0')
        self.e20.insert(0,'0')
        self.e21.insert(0,'0')
        self.e22.insert(0,'0')
        self.e23.insert(0,'0')
        self.e24.insert(0,'0')
        self.e25.insert(0,'0')
        self.e26.insert(0,'0')
        self.e27.insert(0,'0')
        self.e28.insert(0,'0')
        self.e30.insert(0,'0')
        self.e31.insert(0,'0')
        self.e32.insert(0,'0')
        self.e33.insert(0,'0')
        self.e34.insert(0,'0')
        self.e35.insert(0,'0')
        self.e36.insert(0,'0')
        self.e37.insert(0,'0')
        self.e38.insert(0,'0')
        self.e40.insert(0,'0')
        self.e41.insert(0,'0')
        self.e42.insert(0,'0')
        self.e43.insert(0,'0')
        self.e44.insert(0,'0')
        self.e45.insert(0,'0')
        self.e46.insert(0,'0')
        self.e47.insert(0,'0')
        self.e48.insert(0,'0')
        self.e50.insert(0,'0')
        self.e51.insert(0,'0')
        self.e52.insert(0,'0')
        self.e53.insert(0,'0')
        self.e54.insert(0,'0')
        self.e55.insert(0,'0')
        self.e56.insert(0,'0')
        self.e57.insert(0,'0')
        self.e58.insert(0,'0')
        self.e60.insert(0,'0')
        self.e61.insert(0,'0')
        self.e62.insert(0,'0')
        self.e63.insert(0,'0')
        self.e64.insert(0,'0')
        self.e65.insert(0,'0')
        self.e66.insert(0,'0')
        self.e67.insert(0,'0')
        self.e68.insert(0,'0')
        self.e70.insert(0,'0')
        self.e71.insert(0,'0')
        self.e72.insert(0,'0')
        self.e73.insert(0,'0')
        self.e74.insert(0,'0')
        self.e75.insert(0,'0')
        self.e76.insert(0,'0')
        self.e77.insert(0,'0')
        self.e78.insert(0,'0')
        self.e80.insert(0,'0')
        self.e81.insert(0,'0')
        self.e82.insert(0,'0')
        self.e83.insert(0,'0')
        self.e84.insert(0,'0')
        self.e85.insert(0,'0')
        self.e86.insert(0,'0')
        self.e87.insert(0,'0')
        self.e88.insert(0,'0')

        self.e00.grid(row=0,column=0,ipady=10,ipadx=10)
        self.e01.grid(row=0,column=1,ipady=10,ipadx=10)
        self.e02.grid(row=0,column=2,ipady=10,ipadx=10)
        self.e03.grid(row=0,column=3,ipady=10,ipadx=10)
        self.e04.grid(row=0,column=4,ipady=10,ipadx=10)
        self.e05.grid(row=0,column=5,ipady=10,ipadx=10)
        self.e06.grid(row=0,column=6,ipady=10,ipadx=10)
        self.e07.grid(row=0,column=7,ipady=10,ipadx=10)
        self.e08.grid(row=0,column=8,ipady=10,ipadx=10)
        self.e10.grid(row=1,column=0,ipady=10,ipadx=10)
        self.e11.grid(row=1,column=1,ipady=10,ipadx=10)
        self.e12.grid(row=1,column=2,ipady=10,ipadx=10)
        self.e13.grid(row=1,column=3,ipady=10,ipadx=10)
        self.e14.grid(row=1,column=4,ipady=10,ipadx=10)
        self.e15.grid(row=1,column=5,ipady=10,ipadx=10)
        self.e16.grid(row=1,column=6,ipady=10,ipadx=10)
        self.e17.grid(row=1,column=7,ipady=10,ipadx=10)
        self.e18.grid(row=1,column=8,ipady=10,ipadx=10)
        self.e20.grid(row=2,column=0,ipady=10,ipadx=10)
        self.e21.grid(row=2,column=1,ipady=10,ipadx=10)
        self.e22.grid(row=2,column=2,ipady=10,ipadx=10)
        self.e23.grid(row=2,column=3,ipady=10,ipadx=10)
        self.e24.grid(row=2,column=4,ipady=10,ipadx=10)
        self.e25.grid(row=2,column=5,ipady=10,ipadx=10)
        self.e26.grid(row=2,column=6,ipady=10,ipadx=10)
        self.e27.grid(row=2,column=7,ipady=10,ipadx=10)
        self.e28.grid(row=2,column=8,ipady=10,ipadx=10)
        self.e30.grid(row=3,column=0,ipady=10,ipadx=10)
        self.e31.grid(row=3,column=1,ipady=10,ipadx=10)
        self.e32.grid(row=3,column=2,ipady=10,ipadx=10)
        self.e33.grid(row=3,column=3,ipady=10,ipadx=10)
        self.e34.grid(row=3,column=4,ipady=10,ipadx=10)
        self.e35.grid(row=3,column=5,ipady=10,ipadx=10)
        self.e36.grid(row=3,column=6,ipady=10,ipadx=10)
        self.e37.grid(row=3,column=7,ipady=10,ipadx=10)
        self.e38.grid(row=3,column=8,ipady=10,ipadx=10)
        self.e40.grid(row=4,column=0,ipady=10,ipadx=10)
        self.e41.grid(row=4,column=1,ipady=10,ipadx=10)
        self.e42.grid(row=4,column=2,ipady=10,ipadx=10)
        self.e43.grid(row=4,column=3,ipady=10,ipadx=10)
        self.e44.grid(row=4,column=4,ipady=10,ipadx=10)
        self.e45.grid(row=4,column=5,ipady=10,ipadx=10)
        self.e46.grid(row=4,column=6,ipady=10,ipadx=10)
        self.e47.grid(row=4,column=7,ipady=10,ipadx=10)
        self.e48.grid(row=4,column=8,ipady=10,ipadx=10)
        self.e50.grid(row=5,column=0,ipady=10,ipadx=10)
        self.e51.grid(row=5,column=1,ipady=10,ipadx=10)
        self.e52.grid(row=5,column=2,ipady=10,ipadx=10)
        self.e53.grid(row=5,column=3,ipady=10,ipadx=10)
        self.e54.grid(row=5,column=4,ipady=10,ipadx=10)
        self.e55.grid(row=5,column=5,ipady=10,ipadx=10)
        self.e56.grid(row=5,column=6,ipady=10,ipadx=10)
        self.e57.grid(row=5,column=7,ipady=10,ipadx=10)
        self.e58.grid(row=5,column=8,ipady=10,ipadx=10)
        self.e60.grid(row=6,column=0,ipady=10,ipadx=10)
        self.e61.grid(row=6,column=1,ipady=10,ipadx=10)
        self.e62.grid(row=6,column=2,ipady=10,ipadx=10)
        self.e63.grid(row=6,column=3,ipady=10,ipadx=10)
        self.e64.grid(row=6,column=4,ipady=10,ipadx=10)
        self.e65.grid(row=6,column=5,ipady=10,ipadx=10)
        self.e66.grid(row=6,column=6,ipady=10,ipadx=10)
        self.e67.grid(row=6,column=7,ipady=10,ipadx=10)
        self.e68.grid(row=6,column=8,ipady=10,ipadx=10)
        self.e70.grid(row=7,column=0,ipady=10,ipadx=10)
        self.e71.grid(row=7,column=1,ipady=10,ipadx=10)
        self.e72.grid(row=7,column=2,ipady=10,ipadx=10)
        self.e73.grid(row=7,column=3,ipady=10,ipadx=10)
        self.e74.grid(row=7,column=4,ipady=10,ipadx=10)
        self.e75.grid(row=7,column=5,ipady=10,ipadx=10)
        self.e76.grid(row=7,column=6,ipady=10,ipadx=10)
        self.e77.grid(row=7,column=7,ipady=10,ipadx=10)
        self.e78.grid(row=7,column=8,ipady=10,ipadx=10)
        self.e80.grid(row=8,column=0,ipady=10,ipadx=10)
        self.e81.grid(row=8,column=1,ipady=10,ipadx=10)
        self.e82.grid(row=8,column=2,ipady=10,ipadx=10)
        self.e83.grid(row=8,column=3,ipady=10,ipadx=10)
        self.e84.grid(row=8,column=4,ipady=10,ipadx=10)
        self.e85.grid(row=8,column=5,ipady=10,ipadx=10)
        self.e86.grid(row=8,column=6,ipady=10,ipadx=10)
        self.e87.grid(row=8,column=7,ipady=10,ipadx=10)
        self.e88.grid(row=8,column=8,ipady=10,ipadx=10)

        Button(self.top,text="SOLVE",background="white",borderwidth=3,fg="green",command=self.get_entries).grid(row=9,column=2,columnspan=3)
        Button(self.top,text="Exit",background="white",borderwidth=3,fg="red",command=self.top.destroy).grid(row=9,column=4,columnspan=3)


        #solve funtion calls the solver.py to solve the sudoku entered by user
    def solve(self):

        #Initially display the sudoku that user enters 
        for i in range (0,9):
            for j in range (0,9):
                Label(self.top1,text=self.sudoku[i][j],font=("font9",15),background="#ffffff").grid(row=i,column=j)

        #Calling solver to solve and consecutively display the solving process
        threading.Thread(target=solver.solve(self.sudoku,self.top1)).start

        

    def get_entries(self):    
        
        # Storing all entries from previous window in string format
        entries = [ 
[ self.e00.get(), self.e01.get(), self.e02.get(), self.e03.get(), self.e04.get(), self.e05.get(), self.e06.get(), self.e07.get(), self.e08.get()], 
[ self.e10.get(), self.e11.get(), self.e12.get(), self.e13.get(), self.e14.get(), self.e15.get(), self.e16.get(), self.e17.get(), self.e18.get()], 
[ self.e20.get(), self.e21.get(), self.e22.get(), self.e23.get(), self.e24.get(), self.e25.get(), self.e26.get(), self.e27.get(), self.e28.get()], 
[ self.e30.get(), self.e31.get(), self.e32.get(), self.e33.get(), self.e34.get(), self.e35.get(), self.e36.get(), self.e37.get(), self.e38.get()],
[ self.e40.get(), self.e41.get(), self.e42.get(), self.e43.get(), self.e44.get(), self.e45.get(), self.e46.get(), self.e47.get(), self.e48.get()],
[ self.e50.get(), self.e51.get(), self.e52.get(), self.e53.get(), self.e54.get(), self.e55.get(), self.e56.get(), self.e57.get(), self.e58.get()], 
[ self.e60.get(), self.e61.get(), self.e62.get(), self.e63.get(), self.e64.get(), self.e65.get(), self.e66.get(), self.e67.get(), self.e68.get()], 
[ self.e70.get(), self.e71.get(), self.e72.get(), self.e73.get(), self.e74.get(), self.e75.get(), self.e76.get(), self.e77.get(), self.e78.get()], 
[ self.e80.get(), self.e81.get(), self.e82.get(), self.e83.get(), self.e84.get(), self.e85.get(), self.e86.get(), self.e87.get(), self.e88.get()]
]
        self.sudoku=[]

        # Converting entries from string to integers
        for entry in entries:
            ints=[]
            for e in entry:
                ints.append(int(e))
            self.sudoku.append(ints)

        # Destroying entries window and creating new window to visualize the solving process
        self.top.destroy()
        self.top1 = Toplevel()
        self.top1.resizable(0,0)
        img = ImageTk.PhotoImage(Image.open(self.grid))
        lbl=Label(self.top1,image=img)
        lbl.image = img
        lbl.grid(row=0,column=0,columnspan=9,rowspan=9)
        self.top1.after(1,threading.Thread(target=self.solve).start)
        Button(self.top1,text ="Exit",background="white",borderwidth=3,fg="red",command=self.top1.destroy).grid(row=9,column=3,columnspan=3)

        
GUI()
